nephila/djangocms-page-meta

setup.py
As of ver 1.0 of django-meta django-meta-mixin is not needed anymore.
Fixes #44
=> Require dajngo-meta>=1.0 and stop depending on django-meta-mixin

djangocms_page_meta/admin.py
Thanks @macolo for suggesting this approach
Code taken from https://github.com/what-digital/djangocms-page-remove-meta-descr
Fix #50
=> Remove description field from page admin

djangocms_page_meta/templatetags/page_meta_tags.py, tests/test_general.py
=> Do not fail if request is not in context

.idea/vcs.xml, CONTRIBUTING.rst, djangocms_page_meta/utils.py, requirements-test.txt
The idea is share the image using the `filer_file.canonical_url` if django-filer is [configured](http://django-filer.readthedocs.io/en/latest/installation.html#canonical-urls) otherwise use the `filer_file.url` property.
=> Filer canonical url

.travis.yml, HISTORY.rst, README.rst, djangocms_page_meta/__init__.py, djangocms_page_meta/cms_toolbars.py, djangocms_page_meta/models.py, djangocms_page_meta/templatetags/page_meta_tags.py, requirements-test.txt, setup.py, tests/test_templatetags.py, tests/test_toolbar.py, tox.ini
* Add Django 1.11
* Add Python 3.6
* Drop django CMS 3.2, 3.3
Incorporate #74 for preview of django CMS 3.5
Fix #74
=> Django 1.11 / Python 3.6

djangocms_page_meta/admin.py, tests/test_adminpage.py
This plugin is incompatible with one (or more) plugins provided by Divio due to the manner in which the PageAdmin is patched - the base class isn't read from the registry.  However, there is no good way to read that class from the registry without accessing private variables from within the CMS.
The method within this PR uses a monkey-patch style which is compatible with Divio's plugins, uses no private member access, should be OK with other changes to the base class, and should be easy to maintain going forward.
=> Change method of patching PageAdmin

djangocms_page_meta/utils.py
Site id was moved from the page object to the node object, starting from 3.5 this now throws a warning. 
This change makes the package future proof for 3.6 while keeping the backward compatibility for 3.4
=> Read site_id from node if it's available

README.rst, docs/usage.rst
Given the number of requests received regarding this, we'd better document this behavior
=> Add documentation on hiding meta description field from the cms

djangocms_page_meta/admin.py, tests/test_adminpage.py
I can't see any use case that needs the page description when creating a page
Addresses https://github.com/nephila/djangocms-page-meta/issues/60#issuecomment-376109024
=> Remove description when creating a CMS page

djangocms_page_meta/cms_toolbars.py
I can't reproduce this, but the fix is quite straightforward, so merging this anyway
Fix #93
=> Be defensive against unexpected page menu layout

.gitignore, .pep8, djangocms_page_meta/cms_toolbars.py, tests/test_adminpage.py, tox.ini
Added `try/except` block for the old `edit_mode` attribute vs the new `edit_mode_active` property.
Also added `try/except` on django urls for support going forward.
=> Fix for CMS edit mode since 3.5

README.rst, djangocms_page_meta/migrations/0001_initial.py
- A field was missed in the initial migration in the previous Django 2.x PR
- Django 2.1 and Django CMS 3.6 compatibility added to README.rst
=> Adding on_delete to a field in the initial migration.

HISTORY.rst, djangocms_page_meta/cms_toolbars.py
The original code called a get() in a loop which causes an n+1 select problem which is equal to the number of languages for the page. Fixed by reducing it to a single query.
=> Fixed n+1 select problem

changes/138.bugfix, pyproject.toml, setup.cfg
Fix `setup.cfg` and `pyproject.toml` package name
Fix #138
=> Fix setup.cfg and pyproject.toml package name

README.rst, addon.json, changes/141.feature, djangocms_page_meta/addon.json, requirements-test.txt, setup.cfg, tox.ini
Update `addon.json` to support django-app-enabler
Update documentation
Fix #141
=> Add configuration for django-app-enabler

.github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml, .pre-commit-config.yaml, .pyup.yml, README.rst, changes/151.bugfix, setup.cfg, tasks.py, tests/test_toolbar.py, tox.ini
Co-authored-by: Viliam Mihálik <viliam.mihalik@smartbase.sk>
Update tools to support Django 3.2 / django CMS 3.10
Remove incompatibilities with django 4.0 even if we cannot support it officially because we need further testing
Fix #149
Fix #151
=> Add support for Django 3.2 / django CMS 3.10

changes/150.bugfix, djangocms_page_meta/cms_toolbars.py, tests/test_toolbar.py
Skip creating toolbar item in page types
Fix #150
=> Skip creating toolbar item in page types

.bumpversion.cfg, .github/workflows/codeql.yml, .github/workflows/lint.yml, .github/workflows/logger.yml, .github/workflows/publish.yml, .github/workflows/test.yml, .pre-commit-config.yaml, .pyup.yml, .readthedocs.yml, changes/157.feature, djangocms_page_meta/__init__.py, djangocms_page_meta/admin.py, djangocms_page_meta/migrations/0001_initial.py, djangocms_page_meta/migrations/0002_auto_20150807_0936.py, djangocms_page_meta/migrations/0003_auto_20151220_1734.py, djangocms_page_meta/migrations/0004_auto_20160409_1852.py, djangocms_page_meta/migrations/0005_pagemeta_fb_pages.py, djangocms_page_meta/migrations/0006_auto_20160423_1859.py, djangocms_page_meta/migrations/0007_auto_20160530_2257.py, djangocms_page_meta/migrations/0008_auto_20160609_0754.py, djangocms_page_meta/migrations/0009_auto_20171230_1954.py, djangocms_page_meta/migrations/0010_auto_20180108_2316.py, djangocms_page_meta/migrations/0011_auto_20190218_1010.py, djangocms_page_meta/migrations/0012_auto_20200706_1230.py, djangocms_page_meta/migrations/0013_auto_20200821_1457.py, pyproject.toml, setup.cfg, tests/test_utils/urls.py, tox.ini
Update repo configuration to 2023 configuration
Fix #157 
Fix #144
=> Update GH actions / linting configuration

changes/173.bugfix, setup.cfg
* Update dependency Filer from v1.2+ to v3.0+
* Prevents error from DjangoCMS Page Meta migration using unavailable Filer migration
Fix #173
* ~~Usage documentation added in case of new features~~[^2]
* ~~Tests added~~[^2]
<details><summary><code>tox</code> output summary</summary>
```
black: OK (0.42=setup[0.02]+cmd[0.39] seconds)
blacken: OK (0.13=setup[0.00]+cmd[0.12] seconds)
docs: OK (1.21=setup[0.01]+cmd[1.20] seconds)
isort: OK (0.12=setup[0.00]+cmd[0.12] seconds)
isort_format: OK (0.13=setup[0.00]+cmd[0.12] seconds)
ruff: OK (0.14=setup[0.00]+cmd[0.04,0.10] seconds)
pypi-description: OK (21.03=setup[0.01]+cmd[0.28,13.29,7.26,0.20] seconds)
towncrier: OK (0.11=setup[0.00]+cmd[0.11] seconds)
py311-django42-cms311: OK (5.35=setup[1.85]+cmd[3.50] seconds)
py311-django41-cms311: OK …
```
=> fix: update version of dep. "filer" 1.2 → 3.0

changes/181.bugfix, djangocms_page_meta/apps.py
Set default_auto_field in AppConfig to avoid migrations problem if DEFAULT_AUTO_FIELD is different
Fix #181
=> Set default_auto_field in AppConfig
